package com.zimbabeats.core.data.remote.youtube.potoken

import android.content.Context
import java.io.Closeable

/**
 * Generates YouTube `poToken`s (proof-of-origin tokens) required by the WEB client to avoid
 * HTTP 403 responses on streaming URLs.
 */
interface PoTokenGenerator : Closeable {

    /**
     * Generates a poToken for the provided [identifier], using the `integrityToken` and
     * `webPoSignalOutput` obtained during initialization. Can be called multiple times.
     */
    suspend fun generatePoToken(identifier: String): String

    /**
     * @return whether the `integrityToken` is expired, in which case all tokens generated by
     * [generatePoToken] will be invalid and a new [PoTokenGenerator] must be created.
     */
    fun isExpired(): Boolean

    interface Factory {
        /**
         * Initializes a [PoTokenGenerator] by loading the BotGuard VM in a hidden WebView,
         * running it, and obtaining an `integrityToken`. The returned generator can then be used
         * multiple times to generate multiple poTokens with [generatePoToken].
         */
        suspend fun newPoTokenGenerator(context: Context): PoTokenGenerator
    }
}
