package com.zimbabeats.core.data.remote.youtube

import android.content.Context
import android.util.Log
import com.zimbabeats.core.data.remote.youtube.potoken.PoTokenProviderImpl
import com.zimbabeats.core.domain.model.music.Track
import io.ktor.http.URLBuilder
import io.ktor.http.parseQueryString
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.downloader.Downloader
import org.schabi.newpipe.extractor.downloader.Request
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptPlayerManager
import org.schabi.newpipe.extractor.services.youtube.YoutubeService
import org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfo
import okhttp3.ConnectionPool
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.Protocol
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * YouTube stream extractor using NewPipe Extractor library.
 *
 * This handles the critical "n" parameter decryption that YouTube uses
 * to throttle/block stream access. NewPipe Extractor has built-in
 * JavaScript interpreter to properly decode these URLs.
 *
 * Based on how SimpMusic handles stream extraction - uses YoutubeJavaScriptPlayerManager
 * to decode the n-parameter on stream URLs.
 */
class NewPipeStreamExtractor(private val context: Context) {

    companion object {
        private const val TAG = "NewPipeExtractor"
        private var isInitialized = false

        // User agent for web requests
        private const val USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    private val poTokenProvider = PoTokenProviderImpl(context)

    /**
     * poToken data needed to attach to manual InnerTube player requests (and their resulting
     * googlevideo stream URLs) so they don't come back as HTTP 403.
     */
    data class StreamingPoTokens(
        val visitorData: String?,
        val playerPoToken: String?,
        val streamingPoToken: String?
    )

    /**
     * Obtains poTokens (via the BotGuard WebView flow) for use with manual InnerTube player
     * requests in [com.zimbabeats.core.data.remote.youtube.music.YouTubeMusicClient].
     */
    suspend fun getStreamingPoTokens(videoId: String): StreamingPoTokens? = withContext(Dispatchers.IO) {
        val result = poTokenProvider.getWebClientPoToken(videoId) ?: return@withContext null
        StreamingPoTokens(result.visitorData, result.playerRequestPoToken, result.streamingDataPoToken)
    }

    /**
     * Result containing stream URL and track info
     */
    data class ExtractionResult(
        val audioUrl: String,
        val title: String,
        val artist: String,
        val duration: Long, // in seconds
        val thumbnailUrl: String
    )

    /**
     * Result containing video stream URL (video+audio combined or video with separate audio)
     */
    data class VideoExtractionResult(
        val videoUrl: String,
        val audioUrl: String?, // For video-only streams that need separate audio
        val title: String,
        val uploaderName: String,
        val duration: Long, // in seconds
        val thumbnailUrl: String,
        val quality: String,
        val subtitles: List<SubtitleInfo> = emptyList()
    )

    /**
     * Subtitle track information
     */
    data class SubtitleInfo(
        val url: String,
        val languageCode: String,
        val languageName: String,
        val format: String, // "vtt", "ttml", etc.
        val isAutoGenerated: Boolean
    )

    /**
     * Initialize NewPipe Extractor (should be called once at app startup)
     */
    suspend fun initialize(): Boolean = withContext(Dispatchers.IO) {
        if (isInitialized) {
            Log.d(TAG, "NewPipe Extractor already initialized")
            return@withContext true
        }

        try {
            Log.d(TAG, "Initializing NewPipe Extractor...")
            NewPipe.init(OkHttpDownloader())
            // Register a WebView/BotGuard-based PoToken provider so the WEB client's
            // googlevideo.com stream URLs don't come back as HTTP 403.
            YoutubeStreamExtractor.setPoTokenProvider(poTokenProvider)
            isInitialized = true
            Log.d(TAG, "NewPipe Extractor initialized successfully")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to initialize NewPipe Extractor", e)
            false
        }
    }

    /**
     * Decode a stream URL using NewPipe's YoutubeJavaScriptPlayerManager.
     * This handles both signature cipher decryption and n-parameter decryption.
     *
     * Based on SimpMusic's NewPipeUtils.getStreamUrl() method.
     */
    fun decodeStreamUrl(url: String?, signatureCipher: String?, videoId: String): String? {
        try {
            Log.d(TAG, "Decoding stream URL for $videoId: ${url?.take(50) ?: signatureCipher?.take(50)}...")

            val decodedUrl = url ?: signatureCipher?.let { cipher ->
                // Parse signature cipher
                val params = parseQueryString(cipher)
                val obfuscatedSignature = params["s"] ?: run {
                    Log.e(TAG, "Could not parse cipher signature")
                    return null
                }
                val signatureParam = params["sp"] ?: run {
                    Log.e(TAG, "Could not parse cipher signature parameter")
                    return null
                }
                val cipherUrl = params["url"]?.let { URLBuilder(it) } ?: run {
                    Log.e(TAG, "Could not parse cipher url")
                    return null
                }

                // Deobfuscate signature using NewPipe's JavaScript interpreter
                cipherUrl.parameters[signatureParam] = YoutubeJavaScriptPlayerManager.deobfuscateSignature(
                    videoId,
                    obfuscatedSignature
                )
                cipherUrl.toString()
            } ?: run {
                Log.e(TAG, "No URL or signature cipher provided")
                return null
            }

            // Decode the n-parameter (throttling parameter) - this is the critical step!
            val finalUrl = YoutubeJavaScriptPlayerManager.getUrlWithThrottlingParameterDeobfuscated(
                videoId,
                decodedUrl
            )

            Log.d(TAG, "Successfully decoded URL for $videoId")
            return finalUrl
        } catch (e: Exception) {
            Log.e(TAG, "Failed to decode stream URL: ${e.message}", e)
            return null
        }
    }

    /**
     * Get signature timestamp needed for player requests.
     * SimpMusic uses this to ensure the signature is valid.
     */
    fun getSignatureTimestamp(videoId: String): Int? {
        return try {
            YoutubeJavaScriptPlayerManager.getSignatureTimestamp(videoId)
        } catch (e: Exception) {
            Log.w(TAG, "Failed to get signature timestamp: ${e.message}")
            null
        }
    }

    /**
     * Extract audio stream URL for a YouTube video ID.
     * Uses StreamInfo.getInfo() which handles decryption internally.
     */
    suspend fun extractAudioStream(videoId: String): ExtractionResult? = withContext(Dispatchers.IO) {
        if (!isInitialized) {
            Log.w(TAG, "NewPipe Extractor not initialized, attempting initialization...")
            if (!initialize()) {
                Log.e(TAG, "Failed to initialize NewPipe Extractor")
                return@withContext null
            }
        }

        try {
            Log.d(TAG, "Extracting audio stream for: $videoId")

            // Use YouTube Music URL for better audio quality
            val url = "https://www.youtube.com/watch?v=$videoId"
            val service = NewPipe.getService(ServiceList.YouTube.serviceId) as YoutubeService
            val streamInfo = StreamInfo.getInfo(service, url)

            if (streamInfo.errors.isNotEmpty()) {
                streamInfo.errors.forEach { Log.w(TAG, "StreamInfo error for $videoId", it) }
            }

            // Get audio streams
            val audioStreams = streamInfo.audioStreams
            Log.d(TAG, "audioStreams=${audioStreams?.size ?: -1}, videoStreams=${streamInfo.videoStreams?.size ?: -1}, videoOnlyStreams=${streamInfo.videoOnlyStreams?.size ?: -1}")
            if (audioStreams.isNullOrEmpty()) {
                Log.e(TAG, "No audio streams found for: $videoId")
                return@withContext null
            }

            // Find best audio stream (highest bitrate)
            val bestAudio = audioStreams
                .filter { !it.content.isNullOrEmpty() }
                .maxByOrNull { it.averageBitrate }

            val audioUrl = bestAudio?.content
            if (audioUrl.isNullOrEmpty()) {
                Log.e(TAG, "No valid audio URL found for: $videoId")
                return@withContext null
            }

            Log.d(TAG, "NewPipe extracted: ${streamInfo.name} (${streamInfo.duration}s)")
            Log.d(TAG, "Audio URL: ${audioUrl.take(80)}...")
            Log.d(TAG, "Audio bitrate: ${bestAudio.averageBitrate}kbps, format: ${bestAudio.format?.name}")

            // Get thumbnail URL from thumbnails list
            val thumbnailUrl = streamInfo.thumbnails.firstOrNull()?.url
                ?: "https://i.ytimg.com/vi/$videoId/mqdefault.jpg"

            ExtractionResult(
                audioUrl = audioUrl,
                title = streamInfo.name ?: "Unknown Title",
                artist = streamInfo.uploaderName ?: "Unknown Artist",
                duration = streamInfo.duration,
                thumbnailUrl = thumbnailUrl
            )

        } catch (e: Exception) {
            Log.e(TAG, "NewPipe extraction failed for $videoId: ${e.message}", e)
            null
        }
    }

    /**
     * Extract VIDEO stream URL for a YouTube video ID.
     * Prioritizes combined video+audio streams (mp4/webm), falls back to video-only + audio.
     * Uses StreamInfo.getInfo() which handles decryption internally.
     * Includes retry mechanism with exponential backoff for slow mobile networks.
     */
    suspend fun extractVideoStream(videoId: String): VideoExtractionResult? = withContext(Dispatchers.IO) {
        extractVideoStreamWithRetry(videoId, maxRetries = 3)
    }

    /**
     * Internal extraction with retry logic for slow mobile networks
     */
    private suspend fun extractVideoStreamWithRetry(
        videoId: String,
        maxRetries: Int = 3
    ): VideoExtractionResult? {
        if (!isInitialized) {
            Log.w(TAG, "NewPipe Extractor not initialized, attempting initialization...")
            if (!initialize()) {
                Log.e(TAG, "Failed to initialize NewPipe Extractor")
                return null
            }
        }

        var lastException: Exception? = null

        repeat(maxRetries) { attempt ->
            try {
                Log.d(TAG, "Extracting video stream for: $videoId (attempt ${attempt + 1}/$maxRetries)")
                val result = extractVideoStreamInternal(videoId)
                if (result != null) {
                    Log.d(TAG, "Successfully extracted stream on attempt ${attempt + 1}")
                    return result
                }
                Log.w(TAG, "Null result on attempt ${attempt + 1}, retrying...")
            } catch (e: Exception) {
                lastException = e
                Log.w(TAG, "Extraction failed on attempt ${attempt + 1}: ${e.message}")
            }

            // Exponential backoff: 1s, 2s, 4s
            if (attempt < maxRetries - 1) {
                val delayMs = 1000L * (1 shl attempt)
                Log.d(TAG, "Waiting ${delayMs}ms before retry...")
                delay(delayMs)
            }
        }

        Log.e(TAG, "All $maxRetries attempts failed for video $videoId")
        lastException?.let { Log.e(TAG, "Last error: ${it.message}", it) }
        return null
    }

    /**
     * Internal extraction logic (single attempt)
     */
    private fun extractVideoStreamInternal(videoId: String): VideoExtractionResult? {
        try {
            Log.d(TAG, "Extracting video stream for: $videoId")

            val url = "https://www.youtube.com/watch?v=$videoId"
            val service = NewPipe.getService(ServiceList.YouTube.serviceId) as YoutubeService
            val streamInfo = StreamInfo.getInfo(service, url)

            // Extract subtitle tracks
            val subtitlesList = try {
                streamInfo.subtitles?.mapNotNull { subtitle ->
                    val url = subtitle.content ?: return@mapNotNull null
                    SubtitleInfo(
                        url = url,
                        languageCode = subtitle.languageTag ?: "unknown",
                        languageName = subtitle.displayLanguageName ?: subtitle.languageTag ?: "Unknown",
                        format = subtitle.format?.name?.lowercase() ?: "vtt",
                        isAutoGenerated = subtitle.isAutoGenerated
                    )
                } ?: emptyList()
            } catch (e: Exception) {
                Log.w(TAG, "Failed to extract subtitles: ${e.message}")
                emptyList()
            }
            Log.d(TAG, "Found ${subtitlesList.size} subtitle tracks")

            // PRIORITY 1: Get combined video+audio streams (preferred for ExoPlayer)
            val videoStreams = streamInfo.videoStreams
            Log.d(TAG, "Found ${videoStreams?.size ?: 0} video streams (combined)")

            // Quality fallback chain for slow mobile networks (based on SimpMusic)
            // Try: highest available → 480p → 360p → any available
            val filteredStreams = videoStreams?.filter { !it.content.isNullOrEmpty() }

            val bestCombined = filteredStreams?.let { streams ->
                // First try to get the highest quality
                val sortedByQuality = streams.sortedWith(
                    compareByDescending<org.schabi.newpipe.extractor.stream.VideoStream> {
                        it.resolution?.replace(Regex("[^0-9]"), "")?.toIntOrNull() ?: 0
                    }.thenByDescending {
                        if (it.format?.name?.contains("MPEG", ignoreCase = true) == true) 1 else 0
                    }
                )

                // Quality fallback chain: try highest, then 480p, then 360p, then any
                sortedByQuality.firstOrNull()
                    ?: streams.find { it.resolution?.contains("480") == true }
                    ?: streams.find { it.resolution?.contains("360") == true }
                    ?: streams.firstOrNull()
            }

            if (bestCombined != null && !bestCombined.content.isNullOrEmpty()) {
                val resolution = bestCombined.resolution ?: "unknown"
                Log.d(TAG, "Using combined stream: $resolution - ${bestCombined.format?.name}")
                Log.d(TAG, "Video URL: ${bestCombined.content.take(80)}...")

                val thumbnailUrl = streamInfo.thumbnails.firstOrNull()?.url
                    ?: "https://i.ytimg.com/vi/$videoId/mqdefault.jpg"

                return VideoExtractionResult(
                    videoUrl = bestCombined.content,
                    audioUrl = null, // Combined stream, no separate audio needed
                    title = streamInfo.name ?: "Unknown Title",
                    uploaderName = streamInfo.uploaderName ?: "Unknown",
                    duration = streamInfo.duration,
                    thumbnailUrl = thumbnailUrl,
                    quality = resolution,
                    subtitles = subtitlesList
                )
            }

            // PRIORITY 2: Video-only stream + separate audio stream
            val videoOnlyStreams = streamInfo.videoOnlyStreams
            val audioStreams = streamInfo.audioStreams

            Log.d(TAG, "No combined streams, trying video-only (${videoOnlyStreams?.size ?: 0}) + audio (${audioStreams?.size ?: 0})")

            // Quality fallback chain for video-only streams (slow mobile network support)
            val filteredVideoOnly = videoOnlyStreams?.filter { !it.content.isNullOrEmpty() }
            val bestVideoOnly = filteredVideoOnly?.let { streams ->
                val sortedByQuality = streams.sortedByDescending {
                    it.resolution?.replace(Regex("[^0-9]"), "")?.toIntOrNull() ?: 0
                }
                // Fallback chain: highest → 480p → 360p → any
                sortedByQuality.firstOrNull()
                    ?: streams.find { it.resolution?.contains("480") == true }
                    ?: streams.find { it.resolution?.contains("360") == true }
                    ?: streams.firstOrNull()
            }

            val bestAudio = audioStreams
                ?.filter { !it.content.isNullOrEmpty() }
                ?.maxByOrNull { it.averageBitrate }

            if (bestVideoOnly != null && !bestVideoOnly.content.isNullOrEmpty()) {
                val resolution = bestVideoOnly.resolution ?: "unknown"
                Log.d(TAG, "Using video-only stream: $resolution with separate audio")

                val thumbnailUrl = streamInfo.thumbnails.firstOrNull()?.url
                    ?: "https://i.ytimg.com/vi/$videoId/mqdefault.jpg"

                return VideoExtractionResult(
                    videoUrl = bestVideoOnly.content,
                    audioUrl = bestAudio?.content, // May need separate audio track
                    title = streamInfo.name ?: "Unknown Title",
                    uploaderName = streamInfo.uploaderName ?: "Unknown",
                    duration = streamInfo.duration,
                    thumbnailUrl = thumbnailUrl,
                    quality = resolution,
                    subtitles = subtitlesList
                )
            }

            Log.e(TAG, "No video streams found for: $videoId")
            return null

        } catch (e: Exception) {
            Log.e(TAG, "NewPipe video extraction failed for $videoId: ${e.message}", e)
            return null
        }
    }

    /**
     * Get all audio streams with itag -> URL mapping.
     * This matches SimpMusic's newPipePlayer() return format.
     */
    suspend fun getAudioStreams(videoId: String): List<Pair<Int, String>> = withContext(Dispatchers.IO) {
        if (!isInitialized) {
            if (!initialize()) {
                return@withContext emptyList()
            }
        }

        try {
            // Use the music.youtube.com watch URL (like SimpMusic) so the YouTube Music
            // service path is used - this returns audio itags for "- Topic" Art Tracks that
            // the regular www.youtube.com path classifies as having no audio streams.
            val url = "https://music.youtube.com/watch?v=$videoId"
            val streamInfo = StreamInfo.getInfo(NewPipe.getService(0), url)

            val streams = streamInfo.audioStreams + streamInfo.videoStreams + streamInfo.videoOnlyStreams
            streams.mapNotNull { stream ->
                val itag = stream.itagItem?.id ?: return@mapNotNull null
                val content = stream.content ?: return@mapNotNull null
                itag to content
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to get audio streams: ${e.message}", e)
            emptyList()
        }
    }

    /**
     * Return every stream NewPipe knows about for this video, normalized to the same
     * `StreamUrl` shape that `InnertubeClient` emits. Used by the download path as a
     * fallback when InnerTube's player endpoint rejects us (HTTP 400 FAILED_PRECONDITION).
     *
     * Maps NewPipe's MediaFormat / VideoStream / AudioStream types to the codec strings
     * we use elsewhere ("avc1", "vp9", "av01", "mp4a", "opus") so DownloadManager's
     * pairing logic Just Works.
     */
    suspend fun getAllStreams(videoId: String): List<StreamUrl> = withContext(Dispatchers.IO) {
        if (!isInitialized) {
            if (!initialize()) return@withContext emptyList()
        }
        try {
            val url = "https://www.youtube.com/watch?v=$videoId"
            val streamInfo = StreamInfo.getInfo(NewPipe.getService(ServiceList.YouTube.serviceId), url)
            val out = mutableListOf<StreamUrl>()

            // Combined (video + audio) streams.
            streamInfo.videoStreams?.forEach { v ->
                val content = v.content ?: return@forEach
                val height = v.resolution?.replace(Regex("[^0-9]"), "")?.toIntOrNull() ?: 0
                val container = v.format?.name?.lowercase() ?: "mp4"
                val codecGuess = guessVideoCodec(container)
                out += StreamUrl(
                    url = content,
                    quality = v.resolution ?: "${height}p",
                    format = normalizeContainer(container),
                    isVideoOnly = false,
                    videoCodec = codecGuess,
                    audioCodec = if (container.contains("mp4")) "mp4a" else "opus",
                    height = height,
                    bitrate = v.bitrate.takeIf { it > 0 } ?: 0,
                    contentLength = -1L
                )
            }

            // Video-only adaptive streams.
            streamInfo.videoOnlyStreams?.forEach { v ->
                val content = v.content ?: return@forEach
                val height = v.resolution?.replace(Regex("[^0-9]"), "")?.toIntOrNull() ?: 0
                val container = v.format?.name?.lowercase() ?: "mp4"
                out += StreamUrl(
                    url = content,
                    quality = "${v.resolution ?: "${height}p"} (video-only)",
                    format = normalizeContainer(container),
                    isVideoOnly = true,
                    videoCodec = guessVideoCodec(container),
                    audioCodec = null,
                    height = height,
                    bitrate = v.bitrate.takeIf { it > 0 } ?: 0,
                    contentLength = -1L
                )
            }

            // Audio-only adaptive streams.
            streamInfo.audioStreams?.forEach { a ->
                val content = a.content ?: return@forEach
                val container = a.format?.name?.lowercase() ?: "m4a"
                val codec = when {
                    container.contains("m4a") || container.contains("mp4") -> "mp4a"
                    container.contains("opus") || container.contains("webm") -> "opus"
                    else -> null
                }
                out += StreamUrl(
                    url = content,
                    quality = "${a.averageBitrate / 1000}kbps",
                    format = normalizeContainer(container),
                    isVideoOnly = false,
                    videoCodec = null,
                    audioCodec = codec,
                    height = 0,
                    bitrate = a.averageBitrate,
                    contentLength = -1L
                )
            }

            Log.d(TAG, "getAllStreams: ${out.size} streams for $videoId " +
                    "(combined=${streamInfo.videoStreams?.size ?: 0} " +
                    "videoOnly=${streamInfo.videoOnlyStreams?.size ?: 0} " +
                    "audioOnly=${streamInfo.audioStreams?.size ?: 0})")
            out
        } catch (e: Exception) {
            Log.e(TAG, "getAllStreams failed for $videoId: ${e.message}", e)
            emptyList()
        }
    }

    /**
     * NewPipe's MediaFormat enum only carries the container name. Codec has to be guessed
     * from the container — YouTube serves H.264 in MP4 and VP9 in WebM for video-only DASH,
     * which matches this mapping for the common cases. Higher-quality WebM may actually be
     * AV1; downstream code handles either via the same transcode path.
     */
    private fun guessVideoCodec(container: String): String = when {
        container.contains("mp4") -> "avc1"
        container.contains("webm") -> "vp9"
        else -> "avc1"
    }

    private fun normalizeContainer(container: String): String = when {
        container.contains("mp4") -> "mp4"
        container.contains("webm") -> "webm"
        container.contains("m4a") -> "m4a"
        container.contains("opus") -> "opus"
        else -> "mp4"
    }

    /**
     * Convert extraction result to Track and stream URL
     */
    fun toPlayerResult(result: ExtractionResult, videoId: String): Pair<String, Track> {
        val track = Track(
            id = videoId,
            title = result.title,
            artistName = result.artist,
            artistId = null,
            albumName = null,
            albumId = null,
            thumbnailUrl = result.thumbnailUrl,
            duration = result.duration * 1000, // Convert to milliseconds
            isExplicit = false
        )
        return result.audioUrl to track
    }

    /**
     * OkHttp-based Downloader for NewPipe Extractor.
     * Based on SimpMusic's NewPipeDownloaderImpl.
     * Optimized for mobile data with HTTP/1.1 and connection pooling.
     */
    private class OkHttpDownloader : Downloader() {

        private val client = okhttp3.OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            // Force HTTP/1.1 to prevent stream reset errors on mobile networks
            .protocols(listOf(Protocol.HTTP_1_1))
            // Connection pooling for mobile efficiency (reuse connections)
            .connectionPool(ConnectionPool(20, 5, TimeUnit.MINUTES))
            .build()

        override fun execute(request: Request): Response {
            val httpMethod = request.httpMethod()
            val url = request.url()
            val headers = request.headers()
            val dataToSend = request.dataToSend()

            val requestBuilder = okhttp3.Request.Builder()
                .url(url)
                .addHeader("User-Agent", USER_AGENT)

            // Handle request body - POST/PUT require a body even if empty
            val body = dataToSend?.toRequestBody()
            requestBuilder.method(httpMethod, body)

            // Add all headers from the request
            headers.forEach { (headerName, headerValueList) ->
                if (headerValueList.size > 1) {
                    requestBuilder.removeHeader(headerName)
                    headerValueList.forEach { headerValue ->
                        requestBuilder.addHeader(headerName, headerValue)
                    }
                } else if (headerValueList.size == 1) {
                    requestBuilder.header(headerName, headerValueList[0])
                }
            }

            val response = client.newCall(requestBuilder.build()).execute()

            // Handle rate limiting
            if (response.code == 429) {
                response.close()
                throw IOException("Rate limited (429) - reCaptcha challenge required for: $url")
            }

            val responseBody = response.body?.string()
            val latestUrl = response.request.url.toString()

            return Response(
                response.code,
                response.message,
                response.headers.toMultimap(),
                responseBody,
                latestUrl
            )
        }
    }
}
